# Site settings
title: Large Scale Machine Learning and Deep Learning
#email: payberah@kth.se
description: > # this means to ignore newlines until "baseurl:"
  KTH Royal Institute of Technology
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://mrlucasch.github.io" # the base hostname & protocol for your site
#twitter_username: lucasch
#github_username:  mrlucasch

# Build settings
markdown: kramdown

# Other options
#permalink: blog/:year/:month/:title
#job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
google_analytics: UA-97213046-2
